### ISSUE TITLE
create a simple landing page

### ISSUE THREAD

**Issue by adventuroussrv** [climoto/climoto#3]
create a basic landing page for Climoto 

https://github.com/climoto

**Comment by pooja-gera** [comment]
Hi, I would like to work on this issue, can you please elaborate a bit more on Climoto and any specific requirements you have for the design? Also you need the developed page or just the design?

**Comment by adventuroussrv** [comment]
Hi @pooja-gera! You are good to make any design and I don't have any requirements.

**Comment by adventuroussrv** [comment]
Climoto an open-source project dedicated & focused on research & developing solutions for climate change issues.

**Comment by adventuroussrv** [comment]
About Climoto

> Climoto an open-source project dedicated & focused on research & developing solutions for climate change issues.
